# Generated by Django 4.2.27 on 2026-01-31 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventario', '0002_alter_ingrediente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dias_visita', models.CharField(blank=True, help_text='Ej: Lunes y Jueves', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='ultimo_costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='stock_actual',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('gr', 'Gramos'), ('lt', 'Litros'), ('ml', 'Mililitros'), ('pz', 'Piezas')], max_length=5),
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('factura_ref', models.CharField(blank=True, help_text='Folio de factura o ticket', max_length=50)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.ingrediente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='CierreDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ventas_totales_sistema', models.DecimalField(decimal_places=2, max_digits=10)),
                ('efectivo_en_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, help_text='Efectivo - Sistema', max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='proveedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.proveedor'),
        ),
    ]
