# Generated by Django 6.0.1 on 2026-01-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detalle_orden',
            new_name='DetalleOrden',
        ),
    ]
