# Generated by Django 6.0.1 on 2026-01-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0002_rename_detalle_orden_detalleorden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
