# Generated by Django 4.2.27 on 2026-01-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0005_alter_categoria_id_alter_configuracionnegocio_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, help_text='Nombre del icono para el frontend', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='mensaje_cierre',
            field=models.CharField(blank=True, help_text='Mensaje para redes sociales', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='ultima_actualizacion_ubicacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platillos/'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='cantidad_necesaria',
            field=models.DecimalField(decimal_places=3, help_text='Cantidad a descontar por venta', max_digits=10),
        ),
    ]
