# Generated by Django 4.2.27 on 2026-03-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0006_categoria_icono_configuracionnegocio_mensaje_cierre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='porcentaje_ganancia',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5),
        ),
    ]
