# Generated by Django 4.2.27 on 2026-01-31 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ventas', '0002_alter_detalleorden_id_alter_orden_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='fecha',
            new_name='creado_en',
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='notas',
            field=models.CharField(blank=True, help_text='Ej: Sin cebolla', max_length=200),
        ),
        migrations.AddField(
            model_name='orden',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente_nombre',
            field=models.CharField(default='Cliente General', max_length=100),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Preparando', 'En preparación'), ('Listo', 'Listo para entregar'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Quién tomó la orden', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
