# Generated by Django 4.2.27 on 2026-01-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_rename_fecha_orden_creado_en_detalleorden_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='inventario_descontado',
            field=models.BooleanField(default=False, help_text='Evita doble descuento'),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
