# Generated by Django 6.0.1 on 2026-01-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_usuarios_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='password',
        ),
    ]
