# Generated by Django 6.0.1 on 2026-01-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_remove_usuarios_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='nombre',
            new_name='usuario',
        ),
    ]
